[workspace]
members = [
  # Facade crate
  "aws_lambda",

  # Sub-crates
  "aws_lambda_events",
  "aws_lambda_runtime",
  "aws_lambda_gateway",

  # Bridge crates
  "aws_lambda_tower_web",

  # Helper crates
  "aws_lambda_cargo",
  "aws_lambda_events_codegen",

]
